Repository Monitoring-Mtl/Serverless-API, pull requests merged in 2023-10, with the labels that each got.

#22 Feature/vehicle-position Issue#15 #16
  .eslintrc.yml
  .gitignore
  index.js
  package-lock.json
  package.json
  serverless.yml
  src/app.js
  src/config/config.js
  src/controller/stmController.js
  src/routes/stmRoutes.js
Labels: enhancement

#24 ESLint on PR Github Action
  .github/workflows/eslint.yml
  package-lock.json
  src/controller/stmController.js
Labels: DevOps

#44 conversion typescript
  .eslintrc.yml
  .gitignore
  jest.config.ts
  package-lock.json
  package.json
  serverless.yml
  src/app.ts
  src/config/config.ts
  src/controller/stmController.js
  src/controller/stmController.ts
  src/index.ts
  src/routes/stmRoutes.js
  src/routes/stmRoutes.ts
  tests/unit/controller/stmController.unit.ts
  tsconfig.json
Labels: enhancement

#45 eslint prettier
  .eslintrc.js
  jest.config.ts
  package-lock.json
  package.json
  src/app.ts
  src/config/config.ts
  src/controller/stmController.ts
  src/index.ts
  src/routes/stmRoutes.ts
  tests/unit/controller/stmController.unit.ts
  tsconfig.json
Labels: bug, enhancement

#42 Feature/caching pipeline
  .github/actions/setup-node/action.yml
  .github/workflows/linting.yml
Labels: enhancement, DevOps

#39 Feature/linting on commit
  package-lock.json
  package.json
  src/routes/stmRoutes.ts
Labels: enhancement, DevOps

#47 fix Prettier
  .eslintrc.js
  .prettierrc.mjs
  jest.config.ts
  package-lock.json
  package.json
  src/app.ts
  src/config/config.ts
  src/controller/stmController.ts
  src/index.ts
  src/routes/stmRoutes.ts
  template.yml
  tests/unit/controller/stmController.unit.ts
  tsconfig.json
Labels: enhancement, DevOps

#51 Feature/pipeline test
  .gitignore
  package.json
  samconfig.toml
  serverless.yml
  src/controller/stmController.ts
  src/index.ts
  src/routes/stmRoutes.ts
  template.yml
  tests/unit/controller/stmController.test.ts
Labels: DevOps

#58 Feature/issue#55
  data/data.ts
  jest.config.ts
  package.json
  serverless.yml
  src/controller/stmController.ts
  src/routes/stmRoutes.ts
  template.yml
Labels: enhancement

#65 add cors
  package-lock.json
  package.json
  src/app.ts
Labels: enhancement

#68 Fix Tests
  .github/workflows/lint-test-workflow.yml
  package-lock.json
  package.json
  src/controller/stmController.ts
  tests/unit/controller/stmController.test.ts
Labels: enhancement

#71 Feature/cors
  data/data.ts
  nodemon.json
  package-lock.json
  package.json
  serverless.yml
  src/controller/stmController.ts
  src/service/athenaService.ts
  src/utils/dataUtils.ts
  tsconfig.json
Labels: enhancement
